#ifndef OURTYPES_H
#define OURTYPES_H

typedef enum {	MENU, JOKOA, SIMETRIKO, INTERCAMBIO, IA, LUCKY_BLOCK, 
				PAUSA, GALDU, IRABAZI,
				BERRIA, KARGATU, ERREPIKAPENAK, ITXI, ALDATU, ERROREA,
				MUSIKA, SOINUA, GORDE} EGOERA;

#endif